### ISSUE TITLE
Pelaaja luokka

### ISSUE THREAD

**Issue by xirtoth** [Joonsar/School-Project#3]
Pelaaja Luokka
muuttujat: 
Position (oma helper luokka)
Health
Pisteet
Money?

Metodit:
- Liikkuminen
- Collision check

Hienoo englannin ja suomen sekoittelua 👍

**Comment by ilkkahanninen1** [comment]
Tuli tässä mielee et kannattasko meiän tehdä ensin joku ukkeli tai liikkuva tyyppi luokka ja sen kautta joko ensin luodaan tyyppi ja sit sitä käytetään luodessa  et millanen tyyppi tai sit periytymisellä. Sais noi liikkeet, nimet, healtit yms metodit ja statsit sit käytettyä vihollisia tai eläimiä tehdessä jos semmosia tulee?

**Comment by xirtoth** [comment]
Kannattaa ehdottomasti! Laitoinkin eilen tonne ideas kohtaa entity luokan. Periytyminen kuulostaa ehkä parhaalta idealta.
