### ISSUE TITLE
Tietokanta systeemi.

### ISSUE THREAD

**Issue by Joonsar** [Joonsar/School-Project#32]
Tein muuten azureen tommosen linux serverin, jossa pyörii nyt sql. Eli saadaan siihen toi mitä tässä ny haettiin, jotkut highscoret(tms). Testailin jo, ja toimii c# ihan hienosti :)

**Comment by xirtoth** [comment]
Okei me unohdetaan ny toi online highscore ainakin hetkellisesti. Ehkä tehdään database vihollisista itemeistä jne. Voidaan myös käyttää jos halutaan jotain tallennusjuttua tohon, mutta se ei oo tärkee tässävälissä

**Comment by xirtoth** [comment]
Local highscore kyllä viä. ehkä dumpataan toi sqlite ja käytetään mysql. ku sillä tein ton nettisivujutun. käytännössä toimii ihan samalla tavalla koodissa.
