### ISSUE TITLE
Kartan luonti

### ISSUE THREAD

**Issue by xirtoth** [Joonsar/School-Project#5]
Mappiin Dicti joka sisältää tiletypen merkin joka jne. eli mapObjctect<TileType, char> mapObject = new Dictionary<Tiletype, char>();;

Mapit:
-  EXTRA: Tekeekö jokanen yhden mapin? pieni (pelissä voisi olla muutama käsin tehty mappi, esim alotus map voisi olla joku kaupunki tms? muut random generoituja?)

**Comment by xirtoth** [comment]
Mutta siis mappi mielestäni omaksi classiksi. esim, että voidaan gamecontrollerista kutsua Map mapX = new Map(ehkä(width), ehkä(height)) (tähän voi lisätä vaikka mitä jos haluaa). Ehkä Map luokkaan joku metodi, joka itseasiassa tekee sen mapin ja tallentaa Array. Eli jos gamecontrollerista kutsutaan Map x = new map(mitäikinä). mun mielestä mapin pitäs sisältää myös siihen kuuluvat entityt. eli List<Entities> jne...

**Comment by Joonsar** [comment]
Tarvii viä näköjään säädellä mappia. ei täysin toimiva vielä. Reunoihin kävellessä # muutetaan pisteeksi. Koko on väärin(voisi vaihtaa 25x25 . Jäikin hieman isompi sinne vielä kun testailin. Mutta projekti etenee. ei ressata
